services:
  # Nginx Reverse Proxy - Only routes to frontend_web for development
  nginx:
    image: nginx:alpine
    container_name: boiler_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend_web
    networks:
      - boiler_network
    restart: no

  # Frontend Web Service (Dashboard UI) - MAIN DEVELOPMENT FOCUS
  frontend_web:
    build:
      context: ./frontend_web
      dockerfile: Dockerfile
    container_name: boiler_frontend_web
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=frontend_web.settings
      - DJANGO_SERVICE_NAME=frontend_web
      - PORT=8000
      # Enable demo user creation during startup (comment out to disable)
      - CREATE_DEMO_USERS=true
    volumes:
      - ./frontend_web:/app
      - /app/__pycache__
      - ./scripts/init/django-init.sh:/app/init.sh:ro
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - boiler_network
    restart: no
    command: ["bash", "/app/init.sh"]

  # Frontend API Service - MINIMAL (Health Check Only)
  frontend_api:
    build:
      context: ./services/frontend_api
      dockerfile: Dockerfile
    container_name: boiler_frontend_api
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=frontend_api.settings
      - DJANGO_SERVICE_NAME=frontend_api
      - PORT=8001
      - USE_SQLITE=true
    volumes:
      - ./services/frontend_api:/app
      - ./scripts/init/django-init.sh:/app/init.sh:ro
    ports:
      - "8001:8001"
    networks:
      - boiler_network
    restart: no
    command: ["bash", "/app/init.sh"]

  # IoT Ingestion Service - MINIMAL (Health Check Only)
  iot_ingestion:
    build:
      context: ./services/iot_ingestion
      dockerfile: Dockerfile
    container_name: boiler_iot_ingestion
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=iot_ingestion.settings
      - DJANGO_SERVICE_NAME=iot_ingestion
      - PORT=8002
      - USE_SQLITE=true
    volumes:
      - ./services/iot_ingestion:/app
      - ./scripts/init/django-init.sh:/app/init.sh:ro
    ports:
      - "8002:8002"
    networks:
      - boiler_network
    restart: no
    command: ["bash", "/app/init.sh"]

  # AI Processor Service - MINIMAL (Health Check Only)
  ai_processor:
    build:
      context: ./services/ai_processor
      dockerfile: Dockerfile
    container_name: boiler_ai_processor
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=ai_processor.settings
      - DJANGO_SERVICE_NAME=ai_processor
      - PORT=8003
      - USE_SQLITE=true
    volumes:
      - ./services/ai_processor:/app
      - ./scripts/init/django-init.sh:/app/init.sh:ro
    ports:
      - "8003:8003"
    networks:
      - boiler_network
    restart: no
    command: ["bash", "/app/init.sh"]

  # Alert Service - MINIMAL (Health Check Only)
  alert_service:
    build:
      context: ./services/alert_service
      dockerfile: Dockerfile
    container_name: boiler_alert_service
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=alert_service.settings
      - DJANGO_SERVICE_NAME=alert_service
      - PORT=8004
      - USE_SQLITE=true
    volumes:
      - ./services/alert_service:/app
      - ./scripts/init/django-init.sh:/app/init.sh:ro
    ports:
      - "8004:8004"
    networks:
      - boiler_network
    restart: no
    command: ["bash", "/app/init.sh"]

  # Primary Database (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: boiler_postgres
    environment:
      POSTGRES_DB: steambytes_core
      POSTGRES_USER: steambytes
      POSTGRES_PASSWORD: ${DB_PASSWORD:-steambytes_dev_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - boiler_network
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steambytes -d steambytes_core"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Time-Series Database (InfluxDB)
  influxdb:
    image: influxdb:2.7
    container_name: boiler_influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: steambytes
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD:-steambytes_influx_password}
      DOCKER_INFLUXDB_INIT_ORG: steambytes
      DOCKER_INFLUXDB_INIT_BUCKET: sensor_data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN:-steambytes_admin_token}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - boiler_network
    restart: no

  # Redis Cache & Session Store
  redis:
    image: redis:7-alpine
    container_name: boiler_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boiler_network
    restart: no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

# Networks
networks:
  boiler_network:
    driver: bridge

# Volumes
volumes:
  postgres_data:
    driver: local
  influxdb_data:
    driver: local
  redis_data:
    driver: local
