# Generated by Django 5.2.4 on 2025-08-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard.organization'),
        ),
    ]
